### ISSUE TITLE
Low Server: Cannot use pipe with response

### ISSUE THREAD

**Issue by jesusvilla** [jkyberneees/0http#13]
First, I want to congratulate you on doing something so simple to use, but so fast.
Both natively and with expressjs (I think that competing against this framework does not hurt you) you can use pipe on the response object in the router, but can't when using low server.

```js
const low = require('0http/lib/server/low')
const cero = require('0http')

const { router, server } = cero({
  server: low()
})

router.get('/image.png', (req, res) => {
  res.setHeader('Content-Type', 'image/png')

  const { createReadStream } = require('fs')
  const readStream = createReadStream('./test.png')
  readStream.pipe(res)
})

server.listen(3000, (socket) => {
  if (socket) {
    console.log('HTTP server ready!')
  }
})
```

Considerations:

To achieve that, the response object must be a Writable Stream.

**Comment by jkyberneees** [comment]
Hi Jesus, thanks for appreciating and liking the project. You are welcome. 

Totally agree, streams are not yet supported and prevent you doing cool operations such as serving files, etc...

Reviewing your PR...

**Comment by jkyberneees** [comment]
Hi Jesus, 
This feature is now live in v2.4.0, please checkout https://github.com/jkyberneees/0http/releases/tag/v2.4.0

Thanks again!
