### ISSUE TITLE
uWS reqWrapper not being a Stream

### ISSUE THREAD

**Issue by schamberg97** [jkyberneees/0http#18]
Hey there again! I've been working on my [side project](https://github.com/fyrejet/fyrejet) that uses code from `low` library, as well as outstanding issues in this project. However, I figured out that only `resWrapper` class extends a `Writeable Stream`. `http.IncomingMessage` extends `Readable Stream`, but `reqWrapper` does not, which breaks a lot of middlewares, especially `raw-body` and  (by extension) `body-parser`. This is partially fixable through ugly hacks or a rewrite of `reqWrapper` (which would require a new major semver). However, I am curious to know, whether there are any specific reasons why `low` library does not implement `reqWrapper` as a `Readabale Stream`?

**Comment by schamberg97** [comment]
I forgot to mention that reimplementing `reqWrapper` will 100% break 1 test ( because it will remove automatic population of `req.body` with HTTP request's body). That will require a major version bump, but would also mean that `low` library is more compatible with existing non-uWS middleware.

**Comment by jkyberneees** [comment]
Hi @schamberg97, thanks for taking your time to improve the `low` server implementation on top of uWebSockets.

Truth is, I won't be actively maintaining this facade implementation in a long-term view, as the performance difference vs Node.js (cluster on) is not that big anymore. 

I would welcome any contribution in case you would like to provide and increase the supported features. We could also externalise `low` as an independent project and we can take it from there (this could be my preferred option). Please let me know.

Best Regards, 
Rolando

**Comment by schamberg97** [comment]
> We could also externalise `low` as an independent project and we can take it from there (this could be my preferred option). 

I think this is the best approach, especially since any change to `low` is going to require a new major version. Moreover, I don't feel that `low` logically fits together with other 0http components, such as sequential router. `low` is just much lower-level than the rest of the framework.

**Comment by jkyberneees** [comment]
I agree, `low` is actually a "low" level HTTP server implementation. 
I will create a separated project this weekend and add you as a collaborator. 

Regards
