### ISSUE TITLE
serve-static w/ low

### ISSUE THREAD

**Issue by ohenepee** [jkyberneees/0http#4]
Can you get Express `serve-static` to work with `low`

**Comment by jkyberneees** [comment]
Hi @ohenepee, unfortunately `serve-static` requires Node.js compatible interfaces. 0http still does not support them. 

However, there is another project that offers compatibility with both express and uWebSocket.js, please have a look:
https://github.com/dalisoft/nanoexpress/blob/master/examples/static.js

Regards

**Comment by ohenepee** [comment]
Thanks
