### ISSUE TITLE
use middleware with find-my-way router

### ISSUE THREAD

**Issue by m-dary-nur** [jkyberneees/0http#6]
hello, can you explain example code how to use middleware like [cors](https://www.npmjs.com/package/cors) in 0http find-my-way router ? 
i just found demos with sequential router,
thank you

**Comment by jkyberneees** [comment]
Hi @m-dary-nur , unfortunately middlewares are not supported on find-my-way, only on sequential. 
You can have a look at restana (https://www.npmjs.com/package/restana), it does offer middlewares support on top of find-my-way.

Regards

**Comment by m-dary-nur** [comment]
I already used restana for my restful api. maybe restana can improve performance like 0http with low uws is a good news, ok thank you for answer, regard
